### ISSUE TITLE
Option "Push commits to Gerrit by default" is not stored per project

### ISSUE THREAD

**Issue by leonard84** [uwolfer/gerrit-intellij-plugin#381] opened 2020-04-07 14:19 UTC
The option `Push commits to Gerrit by default` is a global setting, but it should be a per project setting.

Motivation: Not every project is a gerrit project so using this options leads to the problem, that I either have to check the push to gerrit checkbox on every gerrit commit or having to uncheck it for every non gerrit projects.

**Comment by uwolfer** [comment] 2020-04-08 19:05
Duplicate of #278.

**Closed as completed** 2020-04-08 19:06 UTC
Labels: duplicate

**Comment by reda-alaoui** [comment] 2020-04-26 16:51
Hello,

I don't see how his relates to #278 .
This issue is still present.

**Comment by reda-alaoui** [comment] 2020-04-26 16:53
Is it theoretically possible to have this option stored per project?
I'd like to know before trying to make a pull request.

**Comment by uwolfer** [comment] 2020-04-26 17:36
> I don't see how his relates to #278 .

You are right, I've referenced the wrong issue. Thanks for pointing out. Should be #159.

> I'd like to know before trying to make a pull request.

A PR would be highly welcome, please see  #159 for ideas how to implement.
