### ISSUE TITLE
Support for Multiple Web URLs

### ISSUE THREAD

**Issue by wTylerReid** [uwolfer/gerrit-intellij-plugin#369] opened 2019-10-29 21:42 UTC
I use multiple GoB Hosts for my development.  Could we add a feature which supports multiple Web URLs from the settings page?

Let me know if you need any more details!

**Comment by uwolfer** [comment] 2019-10-30 21:21
Do you need multiple Gerrit instances per project? Or one per IntelliJ project?

**Comment by wTylerReid** [comment] 2019-10-30 21:24
One per IntelliJ Project.

**Comment by uwolfer** [comment] 2019-10-30 21:26
Duplicate of #159.

**Closed as completed by uwolfer** 2019-10-30 21:26 UTC
Labels: question
