### ISSUE TITLE
Gerrit missing from "Push Commits" dialog after migration to PyCharm 2019.1.1

### ISSUE THREAD

**Issue by tingey** [uwolfer/gerrit-intellij-plugin#348] opened 2019-04-07 01:41 UTC
After migrating from from PyCharm 2018.3.5 to 2019.1.1 'Gerrit' is no longer available in the "Push Commits" dialog.

**Comment by uwolfer** [comment] 2019-04-07 07:58
Duplicate of #345.

**Closed as completed by uwolfer** 2019-04-07 07:58 UTC

**Comment by tingey** [comment] 2019-04-07 15:28
Thanks for the quick update.  
I'm on macOS 10.14.4 and next available JB JDK below 11 was "JRE: 1.8.0_112-release-b251 x86_64" which has restored the "Gerrit" checkbox!
