### ISSUE TITLE
Push dialog selects all project repositories  by deafult, regardless Pycharm git settings

### ISSUE THREAD

**Issue by nshavitt** [uwolfer/gerrit-intellij-plugin#344] opened 2019-01-27 08:09 UTC
I'm using the plugin in PyCharm. While this plugin is active, the push dialog selects all repositories, no matters if pycharm settings chooses to work only with the repository applies to the selected files.

'execute branch operations on all roots' is not selected, still the push selects all roots.

If I disable the plugin, all is fine. Resolved the issue together with PYCharm support.

thanks

**Comment by uwolfer** [comment] 2019-02-27 20:04
Duplicate of #182.

**Closed as completed by uwolfer** 2019-02-27 20:04 UTC
