### ISSUE TITLE
Missing scrollbar in some resolutions (with Remote Desktop)

### ISSUE THREAD

**Issue by weflower** [uwolfer/gerrit-intellij-plugin#368] opened 2019-10-26 19:22 UTC
I'm using the Gerrit plugin 1.2.0-146 with IntelliJ 2019.2.3 Community Edition.

When I log in to my machine through Windows Remote Desktop, the push window in the Gerrit plugin does not show a scrollbar. As a result, I can't see the fields or buttons in the bottom part of the window. (Tabbing lets me get to those fields but it doesn't scroll the window itself.)

See screen shot:
<img width="855" alt="intelliJ-missingscroll-with-RDP" src="https://user-images.githubusercontent.com/22036497/67624852-5b7d3280-f804-11e9-954d-67d0c15bec51.png">

**Comment by uwolfer** [comment] 2019-10-31 19:52
Duplicate of #359.

**Closed as completed** 2020-01-18 12:22 UTC
Labels: duplicate
