### ISSUE TITLE
Support mulitiple Web-Url configuration

### ISSUE THREAD

**Issue by coregiu** [uwolfer/gerrit-intellij-plugin#350] opened 2019-04-23 06:33 UTC
Recently, I met a problem. That our gerrit code repository are in two web-url, but the gerrit web url configuration only support one web-url. Sometimes, we have to change to Web-Url configuration to review some codes in another repository.
So, I want this gerrit code review plugin support multiple  Web-Url configuration. Thanks!

**Comment by leoluk** [comment] 2021-03-24 15:44
Duplicate of #159

**Closed as completed** 2021-03-24 15:46 UTC
Labels: enhancement
