### ISSUE TITLE
Unified Diff View

### ISSUE THREAD

**Issue by treuherz** [uwolfer/gerrit-intellij-plugin#309] opened 2018-03-16 16:54 UTC
The diff viewer opened for files in a Gerrit changeset doesn't feature the [Unified viewer|Side-by-side viewer] drop-down that IDEA's normal diff viewer windows have. Is this intentional? It seems like an odd feature to be excluded, given that it's available elsewhere in IDEA and in Gerrit's web UI.

**Comment by uwolfer** [comment] 2018-03-17 09:40
@treuherz: It would be nice to support this diff viewer as well, but last time I have looked into it, the API was quite different which is required for displaying and adding comments.

I'm happy to review any pull request which adds this feature :)

This is a duplicate of #158.

**Closed as completed by uwolfer** 2018-03-17 09:40 UTC
Labels: duplicate
