### ISSUE TITLE
My idea is to install the Gerrit plug-in. When I want to submit the code, the window is not displayed completely.

### ISSUE THREAD

**Issue by wjfwq1314** [uwolfer/gerrit-intellij-plugin#367] opened 2019-10-18 08:04 UTC
My idea version is 2019.2
![1571385739(1)](https://user-images.githubusercontent.com/39670419/67076923-ba1d2d80-f1c0-11e9-8f81-3b8084d1ce00.jpg)
How to see the east below？
The computer resolution has been set, but it's useless。。。

**Comment by uwolfer** [comment] 2019-10-18 08:10
Duplicate of #359. Please post details of your setup in that report (OS, plugin version).

**Closed as completed by uwolfer** 2019-10-18 08:10 UTC
