### ISSUE TITLE
Checkout on MS Windows breaks IDEA's git integration

### ISSUE THREAD

**Issue by eekboom** [uwolfer/gerrit-intellij-plugin#211] opened 2016-04-28 11:45 UTC
Two of our colleagues are using Windows. This bug happens on both machines:
* right-click a change in the gerrit toolwindow and select checkout
* branch is checked out correctly, files are updated
* however IDEA's git integration is broken afterwards:
  * Version Control -> Log is empty
  * review-branch name is not displayed in status bar
  * git push does not find any commits to push
  * etc.

Happens on both IDEA 14 and latest EAP IU-145.970.
git version was 2.7.2, update to 2.8.1 did not change anything
No errors in IDEA's Event Log
IDEA restart does not fix anything

On our linux machines, checkout works fine.

**Comment by uwolfer** [comment] 2016-04-28 18:44
@eekboom: If you could post the output (anonymized) from IntelliJ tab Version Control -> Console after doing this operation, it would probably help.

**Comment by sam0r** [comment] 2016-05-02 07:48
I noticed that it doesn't happen always when you checkout branches, but I will post the output once it happens again.

**Comment by sam0r** [comment] 2016-05-02 08:06
We were able to reproduce it, here's the output:
10:00:27.533: [project-name] git -c core.quotepath=false fetch origin refs/changes/03/12203/5 --progress --prune
git: 'credential-cache' is not a git command. See 'git --help'.
git: 'credential-cache' is not a git command. See 'git --help'.
From https://gerrit.repo.url
* branch            refs/changes/03/12203/5 -> FETCH_HEAD
10:00:28.934: [project-name] git -c core.quotepath=false checkout -b review/username/12203 FETCH_HEAD --
Switched to a new branch 'review/username/12203'
10:00:29.138: [project-name] git -c core.quotepath=false checkout review/username/12203 --
Already on 'review/username/12203'

**Comment by uwolfer** [comment] 2016-05-02 18:34
@sam0r: Thanks for your feedback. This issue looks really strange. The output does not show anything wrong IMHO (just "normal" Git commands). If you do the same on a Linux / OS X setup, you cannot reproduce it?

How do you "fix" this issue? Just checking out another branch helps?

**Comment by eekboom** [comment] 2016-05-03 07:57
Yes, same project on my Linux machine never shows the bug and the very same action on Linux shows the same git output.
And also yes, just checking out another branch fixes the issue.

It also seems to happen on specific gerrit changes only. It seems like some review branches always check out correctly, while others always show the bug.

**Comment by uwolfer** [comment] 2016-05-03 17:03
@eekboom: Thanks for your feedback. Please post any steps you find to reproduce this issue (e.g. a patter for which changes it fails).

It would also be interesting if it breaks also when using Git command line and issuing the same commands manually.

**Comment by sam0r** [comment] 2016-05-04 15:16
So we have been playing around a little and it looks like it could be an issue with special characters (ö and ü in our case). 
If I checkout a branch and my gerrit "Full Name" contains a special character, then the gerrit plugin creates a branch like review/mynamewithspecialcharacter/change-id and the bug occurs.

If I switch to the master on the commandline, rename the branch locally so that it does not contain any special characters, switch back to that branch, then everything is fine in intellij. Only switching to master and back to the branch without renaming doesn't change anything in intellij.

On the other hand, if I simply create a fresh branch in intellij using special characters(like fününü), the same issue occurs. So it could be rather a bug in intellij, rather than the gerrit plugin: 
https://youtrack.jetbrains.com/issue/IDEA-101222

The suggested workaround works for me so far, so it shoudn't be an issue with the gerrit plugin :).

**Comment by uwolfer** [comment] 2016-05-06 15:59
Thanks a lot for your investigations. Since there is a workaround and it will be fixed in IntelliJ (soon), I'll close this issue.

**Closed by uwolfer** 2016-05-06 15:59 UTC
Labels: question
