### ISSUE TITLE
Pushing code review issue to a different branch with a local branch not existing on repository

### ISSUE THREAD

**Issue by YMasliah-neotys** [uwolfer/gerrit-intellij-plugin#428] opened 2022-01-14 10:30 UTC
Hi,
I have an issue when i want to push a code review when I'm on a feature branch not pushed on origin, to another branch pushed to origin.
Exemple: Push to develop from local branch feat/toto

If i push the code review without pushing beforehand the branch feat/toto into the repository, the push is done like this.
git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/feat/toto:refs/heads/refs/for/develop
When i push the branch feat/toto into origin.
git -c credential.helper= -c core.quotepath=false -c log.showSignature=false push --progress --porcelain origin refs/heads/feat/toto:refs/for/develop

![image](https://user-images.githubusercontent.com/67633752/149500820-12f12cdb-2028-44fa-afea-b49413ce5d0f.png)

Config: 
IntelliJ IDEA 2021.3.1
Gerrit 1.2.5-203

Thanks

**Comment by uwolfer** [comment] 2022-01-14 18:59
@YMasliah-neotys: Do you think this is related or the same as #392?

**Comment by YMasliah-neotys** [comment] 2022-01-24 11:05
Yes probably.

We will check if the bug still exist with the next release, thanks

**Comment by uwolfer** [comment] 2022-01-26 08:57
@YMasliah-neotys: Thanks. Please report if it does not fix the bug. Closing as duplicate of #392 for now.

**Closed as completed by uwolfer** 2022-01-26 08:57 UTC
