### ISSUE TITLE
[Feature Request] project-wise gerrit settings

### ISSUE THREAD

**Issue by KingMario** [uwolfer/gerrit-intellij-plugin#276] opened 2017-05-15 03:13 UTC
Could you please add the feature that one can set up the gerrit url and login info per project-base?

Sometimes, we might be in several projects using different gerrit sites or login infos.

Thanks.

**Comment by uwolfer** [comment] 2017-05-15 16:29
Duplicate of #159.

**Closed as completed by uwolfer** 2017-05-15 16:29 UTC
