### ISSUE TITLE
Failed to get Gerrit changes.: Request not successful.

### ISSUE THREAD

**Issue by KazuoD** [uwolfer/gerrit-intellij-plugin#217] opened 2016-05-11 11:46 UTC
I updated the plugin today from 9.7 -> 9.8

and get the following error message:

> Failed to get Gerrit changes.: Request not successful. Message: Bad Request. Status-Code: 400. Content: "CHANGE_ACTIONS"  is not a valid value for "-o".

**Comment by uwolfer** [comment] 2016-05-11 16:32
@KazuoD: What's the version of your Gerrit server?

**Comment by KazuoD** [comment] 2016-05-11 17:58
Version is 2.9.1

**Comment by uwolfer** [comment] 2016-05-11 18:00
@KazuoD: Thanks. Please tell me the URL if it is available in public so I can test against it. Otherwise I will have to setup my own instance with this version.

**Comment by KazuoD** [comment] 2016-05-11 18:02
Also thanks for the quick response @uwolfer . Sadly it's hosted in my company and so private

**Comment by uwolfer** [comment] 2016-05-11 18:34
@KazuoD: I'm not able to reproduce it with my local 2.9.1 setup... Can you always reproduce it? If you apply a filter like displaying merged changes only, does it also happen?

**Comment by KazuoD** [comment] 2016-05-11 19:05
![gerrit_conf](https://cloud.githubusercontent.com/assets/16476135/15192905/a1dc6516-17bb-11e6-805c-cefdfccd957e.PNG)

@uwolfer always when it refreshes/update/loads. I can try to get a docker image from operations tomorrow with our current Gerrit

**Comment by uwolfer** [comment] 2016-05-11 19:32
Ah, I think I see the problem: your error message is translated to German. Only the English error is handled. I have no idea why it is translated aince Gerrit is not translated?!

**Comment by KazuoD** [comment] 2016-05-11 20:00
Ahh!

https://github.com/uwolfer/gerrit-intellij-plugin/blob/intellij14/src/main/java/com/urswolfer/intellij/plugin/gerrit/rest/GerritUtil.java#L331

Duno why it's translated. Maybe some magic from our operations

**Comment by uwolfer** [comment] 2016-05-11 20:26
@KazuoD: Thanks for your help. I will fix it soon and provide you a test build if you tell me what version of IntelliJ you are using.

Is anything else in your Gerrit also translated to German?

**Comment by KazuoD** [comment] 2016-05-11 20:33
I'm using Version 2016.1.2  Build 145.971.

Good question but i dont know if there are more translations. I'll inform you if i find any.

Thanks for your time @uwolfer

**Closed as completed** 2016-05-12 19:32 UTC
